### ISSUE TITLE
fake_request is not a Request

### ISSUE THREAD

**Issue by isomorphisms** [thomasp85/routr#2]
looks like

a) `routr:::Request` is not exported, so I have to `routr:::Request$new()` to make one
b) `fake_request` does not actually inherit from `Request`, so `trivial_router$dispatch( fake_request('whatever') )` fails

Nice package!

**Comment by isomorphisms** [comment]
lmk if you want me to work on this

**Comment by thomasp85** [comment]
Request and response classes have been moved to the reqres package (they were never exported as they were sip while in routr)
