### ISSUE TITLE
Relaying R (handler) errors to R console

### ISSUE THREAD

**Issue by cpsievert** [thomasp85/routr#5]
Looks as though (route handler) errors are relayed in the response to the client (in the body), but I could see use cases where you may also/rather want to relay that error to the R console (makes debugging easier, if nothing else)

```r
library(routr)
library(fiery)

route <- Route$new()
route$add_handler("get", "/", function(request, response, keys, ...) {
  message("Handler was triggered ")
  stop("Oops, something went wrong", call. = FALSE)
  TRUE
})

router <- RouteStack$new()
router$add_route(route, "name")

app <- Fire$new()
app$attach(router)
app$ignite(showcase = TRUE)
```

**Comment by thomasp85** [comment]
Fixed in 582ae86dfcb82b22b5a4dd86dedf432a112d3fec
