### ISSUE TITLE
Issue naming RouteStack

### ISSUE THREAD

**Issue by cpsievert** [thomasp85/routr#6]
Perhaps I'm doing it wrong, but:

```r
> library(routr)
> router <- RouteStack$new()
> router$name <- "some name"
Error in (function ()  : unused argument (quote("some name"))
```

**Comment by thomasp85** [comment]
The `name` field is read-only (I could add a better error message). It is part of the plugin infrastructure where plugins can require other plugins by name - thus it does not make sense to make it user changeable
