### ISSUE TITLE
Provide a way to iterate over route handlers

### ISSUE THREAD

**Issue by cpsievert** [thomasp85/routr#8]
It doesn't seem as though there is a way to iterate over all the handlers of a given route, which could be useful, for example, to add a prefix to every route path

**Comment by thomasp85** [comment]
Are there any other use cases for this that you could think of? For your use case I'd rather add a global mount point for the route...

**Comment by cpsievert** [comment]
> I'd rather add a global mount point for the route

Do you have an example of doing this anywhere?

**Comment by thomasp85** [comment]
The global mount point will get pushed soon - I think it has general applicability besides what we discuss here...

So, optimally you would like a way to map over the paths, and reassign the result?

**Comment by cpsievert** [comment]
> So, optimally you would like a way to map over the paths, and reassign the result?

yep

**Comment by thomasp85** [comment]
are you thinking an interface where you provide a function that gets the method, path, and handler and then reassigns it itself, e.g.

```r
route$remap_handlers(function(method, path, handler) {
  route$add_handler(method, paste0('/prefix', path), handler)
})
```

**Comment by cpsievert** [comment]
Yea, that looks good!
